"""add_model_settings

Revision ID: 2a4a658eb5fe
Revises: a69ca42314c1
Create Date: 2026-03-28 09:41:49.491437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4a658eb5fe'
down_revision: Union[str, Sequence[str], None] = 'a69ca42314c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('price_competition', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_settings')
    # ### end Alembic commands ###
