"""to_send_summary_field_chat

Revision ID: 5d2469d10267
Revises: 2a4a658eb5fe
Create Date: 2026-03-28 13:16:19.252131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2469d10267'
down_revision: Union[str, Sequence[str], None] = '2a4a658eb5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('to_send_summary', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'to_send_summary')
    # ### end Alembic commands ###
