"""add index_to_sent_at_field_message

Revision ID: 720c3686722d
Revises: 5d2469d10267
Create Date: 2026-03-29 19:33:25.047646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720c3686722d'
down_revision: Union[str, Sequence[str], None] = '5d2469d10267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_chat_created'), table_name='messages')
    op.create_index('ix_messages_chat_created', 'messages', ['chat_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_chat_created', table_name='messages')
    op.create_index(op.f('ix_messages_chat_created'), 'messages', ['chat_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
