"""add promt column to model_settings

Revision ID: 97617f1f2040
Revises: 720c3686722d
Create Date: 2026-04-07 23:34:54.437834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97617f1f2040'
down_revision: Union[str, Sequence[str], None] = '720c3686722d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_settings', sa.Column('promt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_settings', 'promt')
    # ### end Alembic commands ###
