"""change_admin_table

Revision ID: a69ca42314c1
Revises: d971ec156c1e
Create Date: 2026-03-27 17:48:27.196536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a69ca42314c1'
down_revision: Union[str, Sequence[str], None] = 'd971ec156c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', name='uq_admin_telegram_id')
    )
    op.create_index(op.f('ix_admins_telegram_id'), 'admins', ['telegram_id'], unique=True)
    op.drop_index(op.f('ix_chat_admins_chat_id'), table_name='chat_admins')
    op.drop_index(op.f('ix_chat_admins_user_id'), table_name='chat_admins')
    op.drop_table('chat_admins')
    op.add_column('messages', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sent_at')
    op.create_table('chat_admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('chat_admins_chat_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_admins_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_admins_pkey')),
    sa.UniqueConstraint('chat_id', 'user_id', name=op.f('uq_chat_user_admin'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_chat_admins_user_id'), 'chat_admins', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_admins_chat_id'), 'chat_admins', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_admins_telegram_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
