"""add_chat_approval_fields

Revision ID: d971ec156c1e
Revises: 263a1ca6d43e
Create Date: 2026-03-24 23:09:04.530302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd971ec156c1e'
down_revision: Union[str, Sequence[str], None] = '263a1ca6d43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_approved', sa.Boolean(), nullable=False))
    op.execute("UPDATE chats SET is_approved = false WHERE is_approved IS NULL")

    op.alter_column('chats', 'is_approved', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'is_approved')
    # ### end Alembic commands ###
